### ISSUE TITLE
What's the tmux theme and zsh prompt you're using in the gif?

### ISSUE THREAD

**Issue by fr3fou** [kutsan/zsh-system-clipboard#28]

**Comment by kutsan** [comment]
Hi Simo! Let me answer them.

1. tmux theme? You mean the colors or the style itself? The style is [here](https://github.com/kutsan/dotfiles/blob/master/.tmux/config/style.tmux) but it's current version of that file and I might have changed it since then, so see the git history if you want. For the other case, colors are [here](https://github.com/kutsan/dotfiles/blob/master/.config/kitty/config/colors.conf). 
1. Prompt is [pure](https://github.com/sindresorhus/pure) but I actually tweaked a little for zsh vi mode's insert and normal mode symbols. You can make that happen with [this](https://github.com/kutsan/dotfiles/blob/5d3de2a478d5cc548a25c5483f922c7a453f868e/.zsh/config/prompt.zsh#L11-L25).

Also, you are free to explore my dotfiles, everthing is there: https://github.com/kutsan/dotfiles.

**Comment by fr3fou** [comment]
thanks!
