### ISSUE TITLE
Support WSL

### ISSUE THREAD

**Issue by yofriadi** [kutsan/zsh-system-clipboard#32]
I notice that this plugin does not work on my WSL specifically WSL 2 but work in my macbook. Thankyou if you would provide this support.

**Comment by doronbehar** [comment]
What is WSL?

**Comment by kutsan** [comment]
We are not familiar with Windows Subsystem for Linux and since I don't have a Windows machine it would be hard to support without testing. Although, it may be easy by adding a new switch case statement like we're doing in below for macOS. The questions are what we are going to get from `$OSTYPE` and how are we going to get and set clipboard content via command-line.

https://github.com/kutsan/zsh-system-clipboard/blob/3df409852be3060a577e49e07ffd5825dbc92e8a/zsh-system-clipboard.zsh#L26-L34

**Comment by yofriadi** [comment]
hmm I do this on my vim config, even though I don't know what it is, will this help maybe
```
" WSL yank support
let s:clip = '/mnt/c/Windows/System32/clip.exe'
if executable(s:clip)
  augroup WSLYank
    autocmd!
    autocmd TextYankPost * if v:event.operator ==# 'y' | call system(s:clip, @0) | endif
  augroup END
endif
```

**Comment by disco0** [comment]
`OSTYPE` parameter should be linux-* in WSL, should be able to match it on the existing linux* glob and then check for WSL specific commands after—e.g. win32yank(.exe), clip(.exe), pwsh.exe.

As a temporary solution for WSL users—[here's an xclip command replacement](https://gist.github.com/disco0/86e1865c68aa8ce3ebb0676157789abb) that operates on the Windows clipboard, it should be handled by the xclip case transparently based on the xclip detection code above.
