### ISSUE TITLE
Error: No such widget `.zsh-system-clipboard-vicmd-vi-yank'

### ISSUE THREAD

**Issue by nerd190** [kutsan/zsh-system-clipboard#36]
This looks great! But Im getting error:
`No such widget .zsh-system-clipboard-vicmd-vi-yank`
![Screenshot_20210327-185540](https://user-images.githubusercontent.com/63571864/112731306-5149f100-8f2e-11eb-8b9c-48ca55921172.jpg)
Thank you!

**Comment by kutsan** [comment]
Thanks!

What's your zsh version and do you use the latest one? Also, can you be sure that you source the plugin file correctly and re-open your terminal to double-check.

**Comment by jjclavijo** [comment]
I had the same exact issue, it was in fact due to a conflict with the [evil-registers](https://github.com/zsh-vi-more/evil-registers) plugin. That plugin trys to overwrite the widgets binded to vi-style editing commands, and relies on the ```.vi-....``` versions of them (which allways exists for builtin widgets and can’t be rebound, according to [the docs](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets)).
 Maybe that was not the OP's issue, but it is surely related.

**Comment by nerd190** [comment]
correct @jjclavijo I was using `evil-registers` too! 👍

**Comment by kutsan** [comment]
I'm marking this as _invalid_ since we can't really do much about the issue you're having. Feel free to create another one if you encounter similar problems in future.
